version: "3.3"
   
services:
  kind_shredder_db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_NAME}
      - POSTGRES_DB=${DB_NAME}
    # volumes:
    #   - ./data/db:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"
    networks:
      kind_shredder:


  backend:
    build: 
      context: .
    environment:
      - DEBUG=True
      - PYTHONUNBUFFERED=1
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_NAME}
      - POSTGRES_DB=${DB_NAME}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - GOOGLE_APPLICATION_CREDENTIALS=${GCLOUD_CRED}
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    networks:
      kind_shredder:
    depends_on:
      - kind_shredder_db
      # - celery-worker
          
  # celery-worker:
  #   command: celery -A kind_shredder_backend worker --loglevel=INFO --concurrency=5 -E 
  #   build: 
  #     context: .
  #   environment:
  #     - DEBUG=True

  #   networks:
  #     kind_shredder:
  #   # depends_on:
  #   #   - kind_shredder_db

networks:
  kind_shredder:
    driver: bridge