# Generated by Django 3.2.7 on 2022-01-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shredder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
